// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEval4.Data;

namespace SEval4.Migrations
{
    [DbContext(typeof(SEvalDBContext))]
    [Migration("20210512183227_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEval4.Models.AgeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AgeGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("deadec40-1e47-413b-b3a5-c3b4f4565437"),
                            Text = "18 - 24 years old",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("4d3e20e8-8eb9-4ace-9e5a-37c43b57ed7b"),
                            Text = "25 - 34 years old",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("f650bd91-732b-4ccf-a3b5-fb6007a881c6"),
                            Text = "35 - 44 years old",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("ecd07c27-72c7-497e-a4e5-7aa4091e0626"),
                            Text = "45 - 54 years old",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("8ad345a8-51aa-40a0-b163-dadee4723459"),
                            Text = "55 - 64 years old",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("18a718de-8bc3-450e-a3ad-80c3d19f4f15"),
                            Text = "65+ years old",
                            Value = 6
                        });
                });

            modelBuilder.Entity("SEval4.Models.ConfidenceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfidenceGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32902ec6-ab46-4493-ab5e-4f9c9e398755"),
                            Text = "No confidence",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("a487303b-0a2e-40ed-9c61-f348b0f4ec98"),
                            Text = "Low confidence",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("da21c479-e8f2-4834-9c36-3c42ba1e28a0"),
                            Text = "Moderate confidence",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("ab07ff7f-dbdd-439d-9bb1-f65ac6276722"),
                            Text = "High confidence",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("67959e9f-b101-4d81-8550-09c231e611fd"),
                            Text = "Full confidence",
                            Value = 5
                        });
                });

            modelBuilder.Entity("SEval4.Models.EducationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EducationGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0aff4eaf-8097-4f74-b6d7-fbf165392715"),
                            Text = "Primary Education",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("63f1051f-99df-4f14-bc79-9372cd796ce6"),
                            Text = "Secondary Education",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("6b15284e-3528-417e-a02e-9e9442abba64"),
                            Text = "Vocational training",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("4ccd83af-27b9-4e0c-a9eb-f9c577dff120"),
                            Text = "Bachelor degree or equivalent",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("2fc9d1df-03c2-418d-840b-2a3a8adb4498"),
                            Text = "Postgraduate Master",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("998ad9f9-426a-4ca4-9c06-9847eeff96a5"),
                            Text = "PhD",
                            Value = 6
                        });
                });

            modelBuilder.Entity("SEval4.Models.ParticipantSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("EducationGroup")
                        .HasColumnType("int");

                    b.Property<int>("HasFormalTraining")
                        .HasColumnType("int");

                    b.Property<int>("HasInformalTraining")
                        .HasColumnType("int");

                    b.Property<int>("HumanConfidence")
                        .HasColumnType("int");

                    b.Property<int>("PhishingConfidence")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionalExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParticipantSurveys");
                });

            modelBuilder.Entity("SEval4.Models.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("916b51a8-dbaa-45c0-bdfb-cc3cde881552"),
                            Description = "Refuse immidately",
                            ScenarioId = 1,
                            Text = "Refuse to help her entirely and hang up the phone.",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("70c3ce1a-9871-4881-bec9-bd8838444d0f"),
                            Description = "Refer to colleague",
                            ScenarioId = 1,
                            Text = "Ask her to contact one of your colleagues since you are on holiday.",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("fa6c2e66-7b9f-455b-8dfa-3fe8c7966fdf"),
                            Description = "Accept immediately",
                            ScenarioId = 1,
                            Text = "Instantly provide her with your login details and wish her a merry Christmas.",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("be666461-9699-43f1-a764-0894ebb6f1d6"),
                            Description = "Ask more questions and decide later",
                            ScenarioId = 1,
                            Text = "Ask her a few complementary questions and based on her answers either provide her with your login details or don’t provide her with any information.",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("5190393e-dc47-46e0-a646-27975103157a"),
                            Description = "Click on the links and decide later",
                            ScenarioId = 2,
                            Text = "Click on the links provided, and have a look at the company’s online profile as well as reviews left by others. If all seems good, get in contact with the recruiter.",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("6966269c-93fa-4d67-81c1-a4a2cc3ee147"),
                            Description = "Accept immediately and provide too much data",
                            ScenarioId = 2,
                            Text = "You have been job hunting for ages and see this as a blessing in disguise. You reply to the email saying that you would appreciate his help and attach a copy of your CV, a copy of your ID and a link to your GitHub account. (Since you know he will most likely request all this information anyway.",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("64ef3932-8e78-462a-859c-d3ab97d22f7e"),
                            Description = "Ignore and block",
                            ScenarioId = 2,
                            Text = "Ignore the email and remove the recruiter from your LinkedIn.",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("666526e5-ef2d-43ff-b6ad-c7cb8ffc7471"),
                            Description = "Use the number to arrange a meeting",
                            ScenarioId = 2,
                            Text = "Give the recruiter a call on one of the two numbers provided and arrange to meet up with him to discuss how he can help you.",
                            Value = 4
                        });
                });

            modelBuilder.Entity("SEval4.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Correct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0fe86b4-3277-4908-96e2-e730ac219445"),
                            Context = "It is snowy outside, and you are enjoying your Christmas vacation that is longer than you have had in some time. This is going to be a much needed vacation. You have been extra careful ensuring that your tasks at work have been divided among colleagues, so that everyone knows who is responsible for what while you are on vacation. You have also informed your most important customer, and he has, with the usual protests, accepted your vacation. You have just poured a glass of mulled wine when the phone rings. You curse your forgetfulness about leaving the phone on before answering. A very apologetic woman presents herself as a newly employed technician of your customer. She tells you that she is very sorry for calling you, but because she is going to upgrade the customer's backup system she needs to know where the files you have worked on can be found. She also wants to know which computer they are located in and what folder, as well as what user-name you have, in order to guarantee that they will be backed up in the new system. You give her this information, and she thanks you and wishes you a Merry Christmas. An hour later she calls again, almost ready to cry. Something has gone wrong with your backup, she suspects, as it has been locked in the system, and she is the only one left over Christmas. It also seems that only your files are causing trouble. She asks if you would consider coming into the customer's office, checking this, something you refuse. She then wonders if you can give her your login information to enable her to quickly check that the files have not been destroyed so that you can both celebrate Christmas in peace. Which action do you take?",
                            Correct = new Guid("00000000-0000-0000-0000-000000000000"),
                            ScenarioId = 1
                        },
                        new
                        {
                            Id = new Guid("79a40d0f-bcae-4f81-bcef-1163a516e8cf"),
                            Context = "You are a Computer Science Honours student at UCT, currently searching for a job. You receive an invite from someone, who you have never met before, on LinkedIn. You have heard that it is a good idea to have a big network on LinkedIn, so you decide to accept the person’s invite. The following day you receive an email from the person you accepted on LinkedIn. The email contains the following message: “Hey, Thanks for connecting with me on LinkedIn. I specialise in placing Software Engineers in Cape Town. I see on your LinkedIn profile that you are currently doing your Computer Science Honours at UCT. When will you be finishing off there? Have you managed to secure a position as of yet post studies? I’d be keen to have a chat with you to find out what It is that really interests you so I know what to keep my eyes peeled for. Would you be keen? Look forward to hearing from you.” The signature of the email contains the recruiter’s full name, his mobile and landline numbers as well as links to his recruitment company’s website and social media accounts. What action do you take?",
                            Correct = new Guid("00000000-0000-0000-0000-000000000000"),
                            ScenarioId = 2
                        });
                });

            modelBuilder.Entity("SEval4.Models.ScenarioResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioResponse");
                });

            modelBuilder.Entity("SEval4.Models.YearGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YearGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ebcb0b5-e899-4163-85db-e15566d4e894"),
                            Text = "1 year or less",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("ad607bb4-ee8a-48af-9f48-eebd41ac517a"),
                            Text = "2 - 3 years",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("9fae0962-bec3-404e-ae9b-f2ce28190218"),
                            Text = "4 - 5 years",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("9c230095-744e-4ee0-a432-e3d1525c9fba"),
                            Text = "6 years or more",
                            Value = 4
                        });
                });

            modelBuilder.Entity("SEval4.Models.ScenarioResponse", b =>
                {
                    b.HasOne("SEval4.Models.Scenario", "Scenario")
                        .WithMany("Responses")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("SEval4.Models.Scenario", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
