// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEval4.Data;

namespace SEval4.Migrations
{
    [DbContext(typeof(SEvalDBContext))]
    partial class SEvalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEval4.Models.AgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "18 - 24 years old"
                        },
                        new
                        {
                            Id = 2,
                            Text = "25 - 34 years old"
                        },
                        new
                        {
                            Id = 3,
                            Text = "35 - 44 years old"
                        },
                        new
                        {
                            Id = 4,
                            Text = "45 - 54 years old"
                        },
                        new
                        {
                            Id = 5,
                            Text = "55 - 64 years old"
                        },
                        new
                        {
                            Id = 6,
                            Text = "65+ years old"
                        });
                });

            modelBuilder.Entity("SEval4.Models.AttemptCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttemptCounts");
                });

            modelBuilder.Entity("SEval4.Models.ConfidenceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfidenceGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "No confidence"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Low confidence"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Moderate confidence"
                        },
                        new
                        {
                            Id = 4,
                            Text = "High confidence"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Full confidence"
                        });
                });

            modelBuilder.Entity("SEval4.Models.EducationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Primary Education"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Secondary Education"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Vocational training"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Bachelor degree or equivalent"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Postgraduate Master"
                        },
                        new
                        {
                            Id = 6,
                            Text = "PhD"
                        });
                });

            modelBuilder.Entity("SEval4.Models.EvalAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("ResponseValue")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EvaluationAnswers");
                });

            modelBuilder.Entity("SEval4.Models.EvalResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EvaluationResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Accept instantly",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Instantly provide her with your login details and wish her a merry Christmas.",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Ask her a few complementary questions and based on her answers either provide her with your login details or do not provide her with any information.",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reject",
                            IsCorrect = true,
                            ScenarioId = 1,
                            Text = "Refuse to help her entirely and hang up the phone.",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Defer to colleague",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Ask her to contact one of your colleagues since you are on holiday.",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Reply to the email, asking her a few complementary questions and based on her answers either provide her your preliminary time report or refuse to send it to her.",
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Validate through 3rd party",
                            IsCorrect = true,
                            ScenarioId = 2,
                            Text = "Contact your superior to find out whether they approve of you sending your preliminary time report to the person requesting it or not.",
                            Value = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Refuse",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Refuse to send her your preliminary time report.",
                            Value = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Accept immediately",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Since you do not have much work to do, you get working on your preliminary time report immediately and email it to the requester as soon as possible.",
                            Value = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Validate through requester-provided links",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "Click on the links provided and have a look at the company's online profile as well as reviews left by others. If all seems good, contact the recruiter.",
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Accept / Call the recruiter's nubmer and arrange a meeting",
                            IsCorrect = true,
                            ScenarioId = 3,
                            Text = "Give the recruiter a call on one of the two numbers provided and arrange a video call with him to discuss how he can help you.",
                            Value = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Give too much data",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "You have been job hunting for ages and see this as a blessing in disguise. You reply to the email saying that you would appreciate his help and attach a copy of your CV, a copy of your ID and a link to your GitHub account. (Since you know he will most likely request all this information anyway.",
                            Value = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "Ignore the email and remove the recruiter from your LinkedIn.",
                            Value = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Enter competition through official means",
                            IsCorrect = true,
                            ScenarioId = 4,
                            Text = "Record your video in a few days but decide to enter the competition yourself instead by going to the official festival website and entering the competition there, without sending the person on Facebook Messenger any of your details.",
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Record your video in a few days and send him your video along with all the information requested, since he only needs it to enter you into the competition.",
                            Value = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Accept and change login details 24h later",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Record your video in a few days and send him your video along with all the information requested, however you are a bit wary about giving out your Facebook login details and decide to change your Facebook password 24 hours after sending it to him.",
                            Value = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Distrust the whole competition",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Decide not to enter the competition at all. Since the person on Facebook was asking for your Facebook login details for the competition, you conclude that the entire competition must be fake and decide that it is best not to enter.",
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ask a friend to check the drive",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "Give the flash drive to a friend and ask them to try identifying the owner by examining the files on their computer.",
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Check drive on virtual machine",
                            IsCorrect = true,
                            ScenarioId = 5,
                            Text = "You decide to install a virtual machine on your computer and use that virtual machine to examine all folders and open all files on the flash drive in an attempt to identify the owner.",
                            Value = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Scan for viruses and check the drive",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "You first scan the flash drive for viruses and if it is found to be virus free, start examining all folders and opening all files stored on the flash drive to hopefully identify the owner.",
                            Value = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Leave the drive where it is",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "Leave the flash drive where it is, without plugging it into any computer or opening any of the files.",
                            Value = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Even though the student is stressed and needs to get into the lab as soon as possible, you decide to ask the student a few questions and based on his/her answers decide on whether to swipe them in or not.",
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "Refuse",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Refuse to help the student at all and tell them they should not have waited till the last minute to submit their assignment and they should always have their student card on them while on campus.",
                            Value = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Swipe the student in immediately, since you know how stressful it is submitting an assignment at the last minute and you know there is no time to waste.",
                            Value = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Defer to reception",
                            IsCorrect = true,
                            ScenarioId = 6,
                            Text = "Give the student directions to the access control offices where the student can prove their identity and hopefully get access to a computer lab within 15 minutes to submit their assignment.",
                            Value = 4
                        },
                        new
                        {
                            Id = 25,
                            Description = "Accept and use his answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You see this as a life saver and decide to use this to your advantage by comparing his answers to yours and using his answers to help you finish your assignment. You then also reply to his email telling him where your answers were different to his.",
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Reject but use his answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You see this as a life saver and decide to use this to your advantage by comparing his answers to yours and using his answers to help you finish your assignment. You do not respond to his email, however, since you do not know him and would not want his answers to be identical to yours out of fear of being caught for plagiarism.",
                            Value = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "Reject and do not use his answers",
                            IsCorrect = true,
                            ScenarioId = 7,
                            Text = "You close the PDF immediately after opening it and delete it. You do not respond to the email and decide to complete your assignment on your own without comparing your answers to the answers sent to you by the student.",
                            Value = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Reject but send him your answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You are terribly busy finishing off your assignment and do not have time to look at his answers. You therefore decide to just send him your assignment so far and say he is welcome to compare answers, but you do not have time.",
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "Deny the new submission link and use the old (original) submission link instead.",
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "Submit the assignment to the new link, without asking any questions.",
                            Value = 2
                        },
                        new
                        {
                            Id = 31,
                            Description = "Confirm through 3rd party",
                            IsCorrect = true,
                            ScenarioId = 8,
                            Text = "You ask your friend whether they also received the email and based on your friend's answer decide where to submit your assignment.",
                            Value = 3
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "You reply to the lecturer's email asking a few complementary questions, before accepting the new link to be correct and submitting to it.",
                            Value = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Ask the guest lecturer a few complementary questions and based on his answers decide whether to provide the information.",
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "Defer to the lecturer",
                            IsCorrect = true,
                            ScenarioId = 9,
                            Text = "Ask the guest lecturer to contact your lecturer directly to obtain this information.",
                            Value = 2
                        },
                        new
                        {
                            Id = 35,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Do not provide the information and do not tell the guest lecturer where to get it as I deem it to be sensitive information.",
                            Value = 3
                        },
                        new
                        {
                            Id = 36,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Provide all the requested information.",
                            Value = 4
                        },
                        new
                        {
                            Id = 37,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I ask several complementary questions before I comply by clicking the download link.",
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Description = "Ask to elaborate and request time to evaluate later",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I ask complementary questions and ask if I can come back to him at a later stage.",
                            Value = 2
                        },
                        new
                        {
                            Id = 39,
                            Description = "Reject",
                            IsCorrect = true,
                            ScenarioId = 10,
                            Text = "I do not comply with his request at all.",
                            Value = 3
                        },
                        new
                        {
                            Id = 40,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I instantly comply and follow the new download link.",
                            Value = 4
                        });
                });

            modelBuilder.Entity("SEval4.Models.EvalScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvaluationScenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Context = "It is snowy outside, and you are enjoying your Christmas vacation that is longer than you have had in some time. This is going to be a much-needed vacation. You have been extra careful ensuring that your tasks at work have been divided among colleagues, so that everyone knows who is responsible for what while you are on vacation. You have also informed your most important customer, and he has, with the usual protests, accepted your vacation. You have just poured a glass of mulled wine when the phone rings. You curse your forgetfulness about leaving the phone on before answering. A very apologetic woman presents herself as a newly employed technician of your customer. She tells you that she is deeply sorry for calling you, but because she is going to upgrade the customer's backup system she needs to know where the files you have worked on can be found. She also wants to know which computer they are located in and what folder, as well as what username you have, in order to guarantee that they will be backed up in the new system. You give her this information, and she thanks you and wishes you a Merry Christmas. An hour later she calls again, almost ready to cry. Something has gone wrong with your backup, she suspects, as it has been locked in the system, and she is the only one left over Christmas. It also seems that only your files are causing trouble. She asks if you would consider coming into the customer's office, checking this, something you refuse. She then wonders if you can give her your login information to enable her to quickly check that the files have not been destroyed so that you can both celebrate Christmas in peace. Which action do you take?",
                            Feedback = "Placeholder feedback 1"
                        },
                        new
                        {
                            Id = 2,
                            Context = "You are sitting at your desk working. It is an ordinary Thursday in late September, and you do not really have all that much to do. You get an email, from a new email address, saying that a new person at your company’s external accounting firm has started to work on the time reports, and she needs your preliminary time report (a document detailing the number of hours you have worked) mailed to her email at the accounting firm as soon as possible, preferably today, as the end of the quarter is coming up and the owners have requested financial information as soon as possible. You do take note, however, that the email address which this email was sent from has the same domain as all other emails which you have received from the accounting firm in the past. In addition, the style of the email’s signature is the same as the style of the signatures of all previous emails received from various other people working at the accounting firm. Which action do you take?",
                            Feedback = "Placeholder feedback 2"
                        },
                        new
                        {
                            Id = 3,
                            Context = "You are a Computer Science Honours student at University of Aberdeen, currently searching for a job. You receive an invite from someone, who you have never met before, on LinkedIn. You have heard that it is a good idea to have an extensive network on LinkedIn, so you decide to accept the person’s invite. The following day you receive an email from the person you accepted on LinkedIn. The email contains the following message: “Hey, Thanks for connecting with me on LinkedIn. I specialise in placing Software Engineers in UK. I see on your LinkedIn profile that you are currently doing your Computer Science Honours at UCT. When will you be finishing off there? Have you managed to secure a position yet post studies? I would be keen to have a chat with you to find out what It is that really interests you, so I know what to keep my eyes peeled for. Would you be keen? Look forward to hearing from you.” The signature of the email contains the recruiter’s full name, his mobile and landline numbers as well as links to his recruitment company’s website and social media accounts. What action do you take?",
                            Feedback = "Placeholder feedback 2"
                        },
                        new
                        {
                            Id = 4,
                            Context = "You receive a message on the Facebook Messenger app from someone who is not your friend on Facebook. The person who sent you the message, claims to be a marketing agent for a local festival. He tells you about a competition to win free tickets to the festival. You really wanted to attend this festival and the sound of winning free tickets gets you very excited, however you decide to have a look at the festival’s website, to confirm there is really a competition running. After having a look at the website, you see that there is really a competition running and that all you must do is submit a video of yourself showing how excited you are about the festival and showing off your festival dance moves. You decide to thank the person who sent you a message on Facebook Messenger, since you are grateful for finding out about this competition. The person responds saying that it is no problem at all, and he is happy to help. He goes on to ask if you would not mind him assisting you with your entry, because, he explains, that if he helps you, he will get commission. You are not all that technically savvy and you would not mind the help, so you respond saying thanking him for his offer and saying that you would really appreciate his help. He responds saying that it is no problem at all. He tells you that all you will need to do is send him your entry video via Facebook Messenger as well as your full name, date of birth and Facebook login details (email and password), since an entry into the competition requires a link to your Facebook account. Which action do you take?",
                            Feedback = "Placeholder feedback 2"
                        });
                });

            modelBuilder.Entity("SEval4.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AllocationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int?>("StudyGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyGroupId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SEval4.Models.ParticipantSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("EducationGroup")
                        .HasColumnType("int");

                    b.Property<int>("HasFormalTraining")
                        .HasColumnType("int");

                    b.Property<int>("HasInformalTraining")
                        .HasColumnType("int");

                    b.Property<int>("HumanConfidence")
                        .HasColumnType("int");

                    b.Property<int>("PhishingConfidence")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionalExperience")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ParticipantSurveys");
                });

            modelBuilder.Entity("SEval4.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Accept instantly",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Instantly provide her with your login details and wish her a merry Christmas.",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Ask her a few complementary questions and based on her answers either provide her with your login details or do not provide her with any information.",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reject",
                            IsCorrect = true,
                            ScenarioId = 1,
                            Text = "Refuse to help her entirely and hang up the phone.",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Defer to colleague",
                            IsCorrect = false,
                            ScenarioId = 1,
                            Text = "Ask her to contact one of your colleagues since you are on holiday.",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Reply to the email, asking her a few complementary questions and based on her answers either provide her your preliminary time report or refuse to send it to her.",
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Validate through 3rd party",
                            IsCorrect = true,
                            ScenarioId = 2,
                            Text = "Contact your superior to find out whether they approve of you sending your preliminary time report to the person requesting it or not.",
                            Value = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Refuse",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Refuse to send her your preliminary time report.",
                            Value = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Accept immediately",
                            IsCorrect = false,
                            ScenarioId = 2,
                            Text = "Since you do not have much work to do, you get working on your preliminary time report immediately and email it to the requester as soon as possible.",
                            Value = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Validate through requester-provided links",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "Click on the links provided and have a look at the company's online profile as well as reviews left by others. If all seems good, contact the recruiter.",
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Accept / Call the recruiter's nubmer and arrange a meeting",
                            IsCorrect = true,
                            ScenarioId = 3,
                            Text = "Give the recruiter a call on one of the two numbers provided and arrange a video call with him to discuss how he can help you.",
                            Value = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Give too much data",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "You have been job hunting for ages and see this as a blessing in disguise. You reply to the email saying that you would appreciate his help and attach a copy of your CV, a copy of your ID and a link to your GitHub account. (Since you know he will most likely request all this information anyway.",
                            Value = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 3,
                            Text = "Ignore the email and remove the recruiter from your LinkedIn.",
                            Value = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Enter competition through official means",
                            IsCorrect = true,
                            ScenarioId = 4,
                            Text = "Record your video in a few days but decide to enter the competition yourself instead by going to the official festival website and entering the competition there, without sending the person on Facebook Messenger any of your details.",
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Record your video in a few days and send him your video along with all the information requested, since he only needs it to enter you into the competition.",
                            Value = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Accept and change login details 24h later",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Record your video in a few days and send him your video along with all the information requested, however you are a bit wary about giving out your Facebook login details and decide to change your Facebook password 24 hours after sending it to him.",
                            Value = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Distrust the whole competition",
                            IsCorrect = false,
                            ScenarioId = 4,
                            Text = "Decide not to enter the competition at all. Since the person on Facebook was asking for your Facebook login details for the competition, you conclude that the entire competition must be fake and decide that it is best not to enter.",
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ask a friend to check the drive",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "Give the flash drive to a friend and ask them to try identifying the owner by examining the files on their computer.",
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Check drive on virtual machine",
                            IsCorrect = true,
                            ScenarioId = 5,
                            Text = "You decide to install a virtual machine on your computer and use that virtual machine to examine all folders and open all files on the flash drive in an attempt to identify the owner.",
                            Value = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Scan for viruses and check the drive",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "You first scan the flash drive for viruses and if it is found to be virus free, start examining all folders and opening all files stored on the flash drive to hopefully identify the owner.",
                            Value = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Leave the drive where it is",
                            IsCorrect = false,
                            ScenarioId = 5,
                            Text = "Leave the flash drive where it is, without plugging it into any computer or opening any of the files.",
                            Value = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Even though the student is stressed and needs to get into the lab as soon as possible, you decide to ask the student a few questions and based on his/her answers decide on whether to swipe them in or not.",
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "Refuse",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Refuse to help the student at all and tell them they should not have waited till the last minute to submit their assignment and they should always have their student card on them while on campus.",
                            Value = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 6,
                            Text = "Swipe the student in immediately, since you know how stressful it is submitting an assignment at the last minute and you know there is no time to waste.",
                            Value = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Defer to reception",
                            IsCorrect = true,
                            ScenarioId = 6,
                            Text = "Give the student directions to the access control offices where the student can prove their identity and hopefully get access to a computer lab within 15 minutes to submit their assignment.",
                            Value = 4
                        },
                        new
                        {
                            Id = 25,
                            Description = "Accept and use his answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You see this as a life saver and decide to use this to your advantage by comparing his answers to yours and using his answers to help you finish your assignment. You then also reply to his email telling him where your answers were different to his.",
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Reject but use his answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You see this as a life saver and decide to use this to your advantage by comparing his answers to yours and using his answers to help you finish your assignment. You do not respond to his email, however, since you do not know him and would not want his answers to be identical to yours out of fear of being caught for plagiarism.",
                            Value = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "Reject and do not use his answers",
                            IsCorrect = true,
                            ScenarioId = 7,
                            Text = "You close the PDF immediately after opening it and delete it. You do not respond to the email and decide to complete your assignment on your own without comparing your answers to the answers sent to you by the student.",
                            Value = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Reject but send him your answers",
                            IsCorrect = false,
                            ScenarioId = 7,
                            Text = "You are terribly busy finishing off your assignment and do not have time to look at his answers. You therefore decide to just send him your assignment so far and say he is welcome to compare answers, but you do not have time.",
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "Deny the new submission link and use the old (original) submission link instead.",
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "Submit the assignment to the new link, without asking any questions.",
                            Value = 2
                        },
                        new
                        {
                            Id = 31,
                            Description = "Confirm through 3rd party",
                            IsCorrect = true,
                            ScenarioId = 8,
                            Text = "You ask your friend whether they also received the email and based on your friend's answer decide where to submit your assignment.",
                            Value = 3
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 8,
                            Text = "You reply to the lecturer's email asking a few complementary questions, before accepting the new link to be correct and submitting to it.",
                            Value = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Ask the guest lecturer a few complementary questions and based on his answers decide whether to provide the information.",
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "Defer to the lecturer",
                            IsCorrect = true,
                            ScenarioId = 9,
                            Text = "Ask the guest lecturer to contact your lecturer directly to obtain this information.",
                            Value = 2
                        },
                        new
                        {
                            Id = 35,
                            Description = "Reject",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Do not provide the information and do not tell the guest lecturer where to get it as I deem it to be sensitive information.",
                            Value = 3
                        },
                        new
                        {
                            Id = 36,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 9,
                            Text = "Provide all the requested information.",
                            Value = 4
                        },
                        new
                        {
                            Id = 37,
                            Description = "Ask to elaborate and decide later",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I ask several complementary questions before I comply by clicking the download link.",
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Description = "Ask to elaborate and request time to evaluate later",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I ask complementary questions and ask if I can come back to him at a later stage.",
                            Value = 2
                        },
                        new
                        {
                            Id = 39,
                            Description = "Reject",
                            IsCorrect = true,
                            ScenarioId = 10,
                            Text = "I do not comply with his request at all.",
                            Value = 3
                        },
                        new
                        {
                            Id = 40,
                            Description = "Accept",
                            IsCorrect = false,
                            ScenarioId = 10,
                            Text = "I instantly comply and follow the new download link.",
                            Value = 4
                        });
                });

            modelBuilder.Entity("SEval4.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Context = "It is snowy outside, and you are enjoying your Christmas vacation that is longer than you have had in some time. This is going to be a much-needed vacation. You have been extra careful ensuring that your tasks at work have been divided among colleagues, so that everyone knows who is responsible for what while you are on vacation. You have also informed your most important customer, and he has, with the usual protests, accepted your vacation. You have just poured a glass of mulled wine when the phone rings. You curse your forgetfulness about leaving the phone on before answering. A very apologetic woman presents herself as a newly employed technician of your customer. She tells you that she is deeply sorry for calling you, but because she is going to upgrade the customer's backup system she needs to know where the files you have worked on can be found. She also wants to know which computer they are located in and what folder, as well as what username you have, in order to guarantee that they will be backed up in the new system. You give her this information, and she thanks you and wishes you a Merry Christmas. An hour later she calls again, almost ready to cry. Something has gone wrong with your backup, she suspects, as it has been locked in the system, and she is the only one left over Christmas. It also seems that only your files are causing trouble. She asks if you would consider coming into the customer's office, checking this, something you refuse. She then wonders if you can give her your login information to enable her to quickly check that the files have not been destroyed so that you can both celebrate Christmas in peace. Which action do you take?"
                        },
                        new
                        {
                            Id = 2,
                            Context = "You are sitting at your desk working. It is an ordinary Thursday in late September, and you do not really have all that much to do. You get an email, from a new email address, saying that a new person at your company’s external accounting firm has started to work on the time reports, and she needs your preliminary time report (a document detailing the number of hours you have worked) mailed to her email at the accounting firm as soon as possible, preferably today, as the end of the quarter is coming up and the owners have requested financial information as soon as possible. You do take note, however, that the email address which this email was sent from has the same domain as all other emails which you have received from the accounting firm in the past. In addition, the style of the email’s signature is the same as the style of the signatures of all previous emails received from various other people working at the accounting firm. Which action do you take?"
                        },
                        new
                        {
                            Id = 3,
                            Context = "You are a Computer Science Honours student at University of Aberdeen, currently searching for a job. You receive an invite from someone, who you have never met before, on LinkedIn. You have heard that it is a good idea to have an extensive network on LinkedIn, so you decide to accept the person’s invite. The following day you receive an email from the person you accepted on LinkedIn. The email contains the following message: “Hey, Thanks for connecting with me on LinkedIn. I specialise in placing Software Engineers in UK. I see on your LinkedIn profile that you are currently doing your Computer Science Honours at UCT. When will you be finishing off there? Have you managed to secure a position yet post studies? I would be keen to have a chat with you to find out what It is that really interests you, so I know what to keep my eyes peeled for. Would you be keen? Look forward to hearing from you.” The signature of the email contains the recruiter’s full name, his mobile and landline numbers as well as links to his recruitment company’s website and social media accounts. What action do you take?"
                        },
                        new
                        {
                            Id = 4,
                            Context = "You receive a message on the Facebook Messenger app from someone who is not your friend on Facebook. The person who sent you the message, claims to be a marketing agent for a local festival. He tells you about a competition to win free tickets to the festival. You really wanted to attend this festival and the sound of winning free tickets gets you very excited, however you decide to have a look at the festival’s website, to confirm there is really a competition running. After having a look at the website, you see that there is really a competition running and that all you must do is submit a video of yourself showing how excited you are about the festival and showing off your festival dance moves. You decide to thank the person who sent you a message on Facebook Messenger, since you are grateful for finding out about this competition. The person responds saying that it is no problem at all, and he is happy to help. He goes on to ask if you would not mind him assisting you with your entry, because, he explains, that if he helps you, he will get commission. You are not all that technically savvy and you would not mind the help, so you respond saying thanking him for his offer and saying that you would really appreciate his help. He responds saying that it is no problem at all. He tells you that all you will need to do is send him your entry video via Facebook Messenger as well as your full name, date of birth and Facebook login details (email and password), since an entry into the competition requires a link to your Facebook account. Which action do you take?"
                        },
                        new
                        {
                            Id = 5,
                            Context = "Whilst walking on campus you see a flash drive lying on the ground. You pick up the flash drive and notice that there are no identifiable traits on the outer shell of the flash drive that can be used to identify the owner. As you have lost several flash drives before, you feel sorry for the owner of this flash drive. You are aware of how much work could potentially be lost that may be saved on the flash drive. Which action do you take?"
                        },
                        new
                        {
                            Id = 6,
                            Context = "Whilst walking towards the entrance turnstile at the computer lab, a person whom you have never met or seen before approaches you. This person is about the same age as you and looks like a fellow student. The person tells you that he has forgotten his student card at home and can now not enter through the turnstile to use the computers in the lab. The person asks if you could assist him with entering through the turnstile by allowing him to swipe in using your student card. Your card allows you to both swipe in and enter the computer lab. The person looks incredibly stressed and tells you he has an assignment due in 15 minutes that he needs to get access to a computer to submit. You know that there are policies in place that disallow swiping in other students to labs, however it will not harm you in any way to swipe in a fellow student and you could help him pass the course by helping him get to a computer to submit his assignment on time. Which action do you take?"
                        },
                        new
                        {
                            Id = 7,
                            Context = "A day before an assignment is due you receive an email from a fellow student. You have never met this student before, but in the email the student says he is in the same class as you and that he got your email address from the participants section on the course’s Blackboard tab. Attached to the email is a PDF of that student’s assignment. The student says that he is not sure if his answers are correct, and he would really appreciate your help. He asks you to please read through his assignment, compare his answers to yours and then let him know if there are any differences. You open the attached PDF and can clearly see that the student has done the assignment. Which action do you take?"
                        },
                        new
                        {
                            Id = 8,
                            Context = "You are busy working in the computer labs on an important assignment that must be handed in within the next 30 minutes. You also have another application open which is monitoring your incoming emails. You receive an email from your lecturer who has given you the assignment and the email is related to the assignment which you are busy with. The email provides you with a different submission link than the one you originally had for submitting the assignment. You are fairly sure that this email is from this lecturer, however it is extremely uncommon for this lecturer to send out emails directly to the students. Communication such as this one is normally communicated via the announcement system on the course’s Blackboard page. Which action do you take?"
                        },
                        new
                        {
                            Id = 9,
                            Context = "You are sitting in one of the classes that you attend every week. Your lecturer walks into the class and introduces a guest lecturer to you from an external organisation. The guest lecturer provides a brief explanation about his organisation and that he is extremely grateful to be speaking directly to the students. The guest lecturer provides the students with a small assignment to perform. The guest lecturer informs the students that this assignment will count towards their marks for the end of the year. Upon receiving the assignment, you find that apart from requesting your student number, you are also requested to provide your date of birth as well as the last 4 digits of your identification document (ID) number. While you are considering whether you are going to provide this information, the guest lecturer assures you that this information will only be used for recruitment purposes later on. Which action do you take?"
                        },
                        new
                        {
                            Id = 10,
                            Context = "You have been working on a major project for a customer for a long time. The project has been quite stressful in periods, and calmer in others. It has been a rewarding project, and you think it is a little sad that it is soon to end. The project has involved a number of offices in several countries, as well as many people. The project also uses special software, especially developed for this project. You do not know that much about how it works, as you have mostly been involved at an overall level. At the moment you are sitting trying to finish the last of this week's documentation in order to leave for the weekend. You get a call from a 'Jacob', from technical support, which is stationed in San Francisco. He explains that you seem to be running a previous version of the software, something that has given them severe problems as it hinders the encryption from working correctly, because it uses another system for the public keys. Jacob directs you to a link where a more recent version can be found and asks you to install it as soon as possible and to log in again to stop the problems."
                        });
                });

            modelBuilder.Entity("SEval4.Models.StudyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = new Guid("38e321c8-43ff-4289-9a0a-553097acf405"),
                            Name = "SEADM"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = new Guid("869ae0a0-29ec-4aa5-bfa1-8ec86c56f9e9"),
                            Name = "Feedback"
                        });
                });

            modelBuilder.Entity("SEval4.Models.SurveyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("ResponseValue")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SurveyAnswers");
                });

            modelBuilder.Entity("SEval4.Models.YearGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YearGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "1 year or less"
                        },
                        new
                        {
                            Id = 2,
                            Text = "2 - 3 years"
                        },
                        new
                        {
                            Id = 3,
                            Text = "4 - 5 years"
                        },
                        new
                        {
                            Id = 4,
                            Text = "6 years or more"
                        });
                });

            modelBuilder.Entity("SEval4.Models.AttemptCount", b =>
                {
                    b.HasOne("SEval4.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SEval4.Models.Participant", b =>
                {
                    b.HasOne("SEval4.Models.StudyGroup", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId");

                    b.Navigation("StudyGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
